::kaatu::காட்டு
::khatu::காட்டு
::khattu::காட்டு
::khathu::காட்டு
::khaatu::காட்டு
::khaathu::காட்டு
::kaathu::காட்டு
::vaangu::வாங்கு
::vangu::வாங்கு
::vhanghu::வாங்கு
::vhangu::வாங்கு
::vaanghu::வாங்கு
::matrum::மற்றும்
::mattrum::மற்றும்
::matruhm::மற்றும்
::maatrum::மற்றும்
::alladhu::அல்லது
::aladhu::அல்லது
::alladu::அல்லது
::aladu::அல்லது
::allathu::அல்லது
::allatu::அல்லது
::alathu::அல்லது
::alatu::அல்லது
::illai::இல்லை
::ilai::இல்லை
::sari::சரி
::seri::சரி
::thavaru::தவறு
::tavaru::தவறு
::tavarhu::தவறு
::thavarhu::தவறு
::sariyenil::சரியெனில்
::seriyenil::சரியெனில்
::alladhenil::அல்லதெனில்
::allathenil::அல்லதெனில்
::thavarenil::தவறெனில்
::tavarenil::தவறெனில்
::mudi::முடி
::moodi::முடி
::mudhi::முடி
::unmaivarai::உண்மைவரை
::onmaivarai::உண்மைவரை
::oonmaivarai::உண்மைவரை
::unmhaivarai::உண்மைவரை
::unmhaivharhai::உண்மைவரை
::unmhaivarhai::உண்மைவரை
::unmhaivharai::உண்மைவரை
::unmaivharhai::உண்மைவரை
::unmaivarhai::உண்மைவரை
::unmaivharai::உண்மைவரை
::thirumbachei::திரும்பச்செய்
::tirumbachei::திரும்பச்செய்
::thirumbasei::திரும்பச்செய்
::tirumbasei::திரும்பச்செய்
::seyalbaagam::செயல்பாகம்
::seyalpaagam::செயல்பாகம்
::seyalbagam::செயல்பாகம்
::seyalpagam::செயல்பாகம்
::velikodu::வெளிகொடு
::velikkodu::வெளிகொடு
::vellikodu::வெளிகொடு
::niruthu::நிறுத்து
::nirutthu::நிறுத்து
::nirutu::நிறுத்து
::niruttu::நிறுத்து
::thodar::தொடர்
::todar::தொடர்
::thotar::தொடர்
::totar::தொடர்
::muluen::முழுஎண்
::mhuluyen::முழுஎண்
::mhuluen::முழுஎண்
::muluyen::முழுஎண்
::pulliyen::புள்ளிஎண்
::pullien::புள்ளிஎண்
::puliyen::புள்ளிஎண்
::pulien::புள்ளிஎண்
::vaakiyam::வாக்கியம்
::vakiyam::வாக்கியம்
::vaakiam::வாக்கியம்
::vakiam::வாக்கியம்
::pattiyal::பட்டியல்
::patiyal::பட்டியல்
::pathiyal::பட்டியல்
::patthiyal::பட்டியல்
::patial::பட்டியல்
::pattial::பட்டியல்
::inai::இணை
::inay::இணை
::inhai::இணை
::vagai::வகை
::vhagai::வகை
::vhaghai::வகை
::vaghai::வகை
::veliyeru::வெளியேறு
::veliyehru::வெளியேறு
::veliyerru::வெளியேறு
::vehliyeru::வெளியேறு
::veliyerhu::வெளியேறு
::veliyehru::வெளியேறு
::veliyehrhu::வெளியேறு
::thiran::திறன்
::tiran::திறன்
::niral::நிரல்
::neral::நிரல்
::mozhi::மொழி
::mohli::மொழி
::moli::மொழி
::molhi::மொழி