::kaatu::காட்டு
::khatu::காட்டு
::khattu::காட்டு
::khathu::காட்டு
::khaatu::காட்டு
::khaathu::காட்டு
::kaathu::காட்டு
::vaangu::வாங்கு
::vangu::வாங்கு
::vhanghu::வாங்கு
::vhangu::வாங்கு
::vaanghu::வாங்கு
::matrum::மற்றும்
::mattrum::மற்றும்
::matruhm::மற்றும்
::maatrum::மற்றும்
::alladhu::அல்லது
::aladhu::அல்லது
::alladu::அல்லது
::aladu::அல்லது
::allathu::அல்லது
::allatu::அல்லது
::alathu::அல்லது
::alatu::அல்லது
::illai::இல்லை
::ilai::இல்லை
::sari::சரி
::seri::சரி
::thavaru::தவறு
::tavaru::தவறு
::tavarhu::தவறு
::thavarhu::தவறு
::sariyenil::சரியெனில்
::seriyenil::சரியெனில்
::alladhenil::அல்லதெனில்
::allathenil::அல்லதெனில்
::thavarenil::தவறெனில்
::tavarenil::தவறெனில்
::mudi::முடி
::moodi::முடி
::mudhi::முடி
::unmaivarai::உண்மைவரை
::onmaivarai::உண்மைவரை
::oonmaivarai::உண்மைவரை
::unmhaivarai::உண்மைவரை
::unmhaivharhai::உண்மைவரை
::unmhaivarhai::உண்மைவரை
::unmhaivharai::உண்மைவரை
::unmaivharhai::உண்மைவரை
::unmaivarhai::உண்மைவரை
::unmaivharai::உண்மைவரை
::thirumbachei::திரும்பச்செய்
::tirumbachei::திரும்பச்செய்
::thirumbasei::திரும்பச்செய்
::tirumbasei::திரும்பச்செய்
::seyalbaagam::செயல்பாகம்
::seyalpaagam::செயல்பாகம்
::seyalbagam::செயல்பாகம்
::seyalpagam::செயல்பாகம்
::velikodu::வெளிகொடு
::velikkodu::வெளிகொடு
::vellikodu::வெளிகொடு
::niruthu::நிறுத்து
::nirutthu::நிறுத்து
::nirutu::நிறுத்து
::niruttu::நிறுத்து
::thodar::தொடர்
::todar::தொடர்
::thotar::தொடர்
::totar::தொடர்
::muluen::முழுஎண்
::mhuluyen::முழுஎண்
::mhuluen::முழுஎண்
::muluyen::முழுஎண்
::pulliyen::புள்ளிஎண்
::pullien::புள்ளிஎண்
::puliyen::புள்ளிஎண்
::pulien::புள்ளிஎண்
::vaakiyam::வாக்கியம்
::vakiyam::வாக்கியம்
::vaakiam::வாக்கியம்
::vakiam::வாக்கியம்
::pattiyal::பட்டியல்
::patiyal::பட்டியல்
::pathiyal::பட்டியல்
::patthiyal::பட்டியல்
::patial::பட்டியல்
::pattial::பட்டியல்
::vagai::வகை
::vhagai::வகை
::vhaghai::வகை
::vaghai::வகை
::veliyeru::வெளியேறு
::veliyehru::வெளியேறு
::veliyerru::வெளியேறு
::vehliyeru::வெளியேறு
::veliyerhu::வெளியேறு
::veliyehru::வெளியேறு
::veliyehrhu::வெளியேறு
::pattiyal_inai::பட்டியல்_இணை
::patiyal_inai::பட்டியல்_இணை
::pathiyal_inai::பட்டியல்_இணை
::patthiyal_inai::பட்டியல்_இணை
::patial_inai::பட்டியல்_இணை
::pattial_inai::பட்டியல்_இணை
::pattiyal_inay::பட்டியல்_இணை
::patiyal_inay::பட்டியல்_இணை
::pathiyal_inay::பட்டியல்_இணை
::patthiyal_inay::பட்டியல்_இணை
::patial_inay::பட்டியல்_இணை
::pattial_inay::பட்டியல்_இணை
::pattiyal_inhai::பட்டியல்_இணை
::patiyal_inhai::பட்டியல்_இணை
::pathiyal_inhai::பட்டியல்_இணை
::patthiyal_inhai::பட்டியல்_இணை
::patial_inhai::பட்டியல்_இணை
::pattial_inhai::பட்டியல்_இணை
::pattiyal_sher::பட்டியல்_சேர்
::patiyal_sher::பட்டியல்_சேர்
::pathiyal_sher::பட்டியல்_சேர்
::patthiyal_sher::பட்டியல்_சேர்
::patial_sher::பட்டியல்_சேர்
::pattial_sher::பட்டியல்_சேர்
::pattiyal_ser::பட்டியல்_சேர்
::patiyal_ser::பட்டியல்_சேர்
::pathiyal_ser::பட்டியல்_சேர்
::patthiyal_ser::பட்டியல்_சேர்
::patial_ser::பட்டியல்_சேர்
::pattial_ser::பட்டியல்_சேர்
::pattiyal_cher::பட்டியல்_சேர்
::patiyal_cher::பட்டியல்_சேர்
::pathiyal_cher::பட்டியல்_சேர்
::patthiyal_cher::பட்டியல்_சேர்
::patial_cher::பட்டியல்_சேர்
::pattial_cher::பட்டியல்_சேர்
::pattiyal_cer::பட்டியல்_சேர்
::patiyal_cer::பட்டியல்_சேர்
::pathiyal_cer::பட்டியல்_சேர்
::patthiyal_v::பட்டியல்_சேர்
::patial_cer::பட்டியல்_சேர்
::pattial_cer::பட்டியல்_சேர்
::pattiyal_neeku::பட்டியல்_நீக்கு
::patiyal_neeku::பட்டியல்_நீக்கு
::pathiyal_neeku::பட்டியல்_நீக்கு
::patthiyal_neeku::பட்டியல்_நீக்கு
::patial_neeku::பட்டியல்_நீக்கு
::pattial_neeku::பட்டியல்_நீக்கு
::pattiyal_niku::பட்டியல்_நீக்கு
::patiyal_niku::பட்டியல்_நீக்கு
::pathiyal_niku::பட்டியல்_நீக்கு
::patthiyal_niku::பட்டியல்_நீக்கு
::patial_niku::பட்டியல்_நீக்கு
::pattial_niku::பட்டியல்_நீக்கு
::pattiyal_neekhu::பட்டியல்_நீக்கு
::patiyal_neekhu::பட்டியல்_நீக்கு
::pathiyal_neekhu::பட்டியல்_நீக்கு
::patthiyal_neekhu::பட்டியல்_நீக்கு
::patial_neekhu::பட்டியல்_நீக்கு
::pattial_neekhu::பட்டியல்_நீக்கு
::pattiyal_nikhu::பட்டியல்_நீக்கு
::patiyal_nikhu::பட்டியல்_நீக்கு
::pathiyal_nikhu::பட்டியல்_நீக்கு
::patthiyal_nikhu::பட்டியல்_நீக்கு
::patial_nikhu::பட்டியல்_நீக்கு
::pattial_nikhu::பட்டியல்_நீக்கு
::pattiyal_neku::பட்டியல்_நீக்கு
::patiyal_neku::பட்டியல்_நீக்கு
::pathiyal_neku::பட்டியல்_நீக்கு
::patthiyal_neku::பட்டியல்_நீக்கு
::patial_neku::பட்டியல்_நீக்கு
::pattial_neku::பட்டியல்_நீக்கு
::pattiyal_surukku::பட்டியல்_சுருக்கு
::patiyal_surukku::பட்டியல்_சுருக்கு
::pathiyal_surukku::பட்டியல்_சுருக்கு
::patthiyal_surukku::பட்டியல்_சுருக்கு
::patial_surukku::பட்டியல்_சுருக்கு
::pattial_surukku::பட்டியல்_சுருக்கு
::pattiyal_suruku::பட்டியல்_சுருக்கு
::patiyal_suruku::பட்டியல்_சுருக்கு
::pathiyal_suruku::பட்டியல்_சுருக்கு
::patthiyal_suruku::பட்டியல்_சுருக்கு
::patial_suruku::பட்டியல்_சுருக்கு
::pattial_suruku::பட்டியல்_சுருக்கு
::pattiyal_shurukhu::பட்டியல்_சுருக்கு
::patiyal_shurukhu::பட்டியல்_சுருக்கு
::pathiyal_shurukhu::பட்டியல்_சுருக்கு
::patthiyal_shurukhu::பட்டியல்_சுருக்கு
::patial_shurukhu::பட்டியல்_சுருக்கு
::pattial_shurukhu::பட்டியல்_சுருக்கு
::pattiyal_surukkhu::பட்டியல்_சுருக்கு
::patiyal_surukkhu::பட்டியல்_சுருக்கு
::pathiyal_surukkhu::பட்டியல்_சுருக்கு
::patthiyal_surukkhu::பட்டியல்_சுருக்கு
::patial_surukkhu::பட்டியல்_சுருக்கு
::pattial_surukkhu::பட்டியல்_சுருக்கு
::pattiyal_neelam::பட்டியல்_நீளம்
::patiyal_neelam::பட்டியல்_நீளம்
::pathiyal_neelam::பட்டியல்_நீளம்
::patthiyal_neelam::பட்டியல்_நீளம்
::patial_neelam::பட்டியல்_நீளம்
::pattial_neelam::பட்டியல்_நீளம்
::pattiyal_nelam::பட்டியல்_நீளம்
::patiyal_nelam::பட்டியல்_நீளம்
::pathiyal_nelam::பட்டியல்_நீளம்
::patthiyal_nelam::பட்டியல்_நீளம்
::patial_nelam::பட்டியல்_நீளம்
::pattial_nelam::பட்டியல்_நீளம்
::pattiyal_nhelam::பட்டியல்_நீளம்
::patiyal_nhelam::பட்டியல்_நீளம்
::pathiyal_nhelam::பட்டியல்_நீளம்
::patthiyal_nhelam::பட்டியல்_நீளம்
::patial_nhelam::பட்டியல்_நீளம்
::pattial_nhelam::பட்டியல்_நீளம்
::pattiyal_neelham::பட்டியல்_நீளம்
::patiyal_neelham::பட்டியல்_நீளம்
::pathiyal_neelham::பட்டியல்_நீளம்
::patthiyal_neelham::பட்டியல்_நீளம்
::patial_neelham::பட்டியல்_நீளம்
::pattial_neelham::பட்டியல்_நீளம்
::pattiyal_nilam::பட்டியல்_நீளம்
::patiyal_nilam::பட்டியல்_நீளம்
::pathiyal_nilam::பட்டியல்_நீளம்
::patthiyal_nilam::பட்டியல்_நீளம்
::patial_nilam::பட்டியல்_நீளம்
::pattial_nilam::பட்டியல்_நீளம்
::pattiyal_niilam::பட்டியல்_நீளம்
::patiyal_niilam::பட்டியல்_நீளம்
::pathiyal_niilam::பட்டியல்_நீளம்
::patthiyal_niilam::பட்டியல்_நீளம்
::patial_niilam::பட்டியல்_நீளம்
::pattial_niilam::பட்டியல்_நீளம்
::pattiyal_nilham::பட்டியல்_நீளம்
::patiyal_nilham::பட்டியல்_நீளம்
::pathiyal_nilham::பட்டியல்_நீளம்
::patthiyal_nilham::பட்டியல்_நீளம்
::patial_nilham::பட்டியல்_நீளம்
::pattial_nilham::பட்டியல்_நீளம்
::inai::இணை
::inay::இணை
::inhai::இணை